### ISSUE TITLE
IDA Loader for GBA 

### ISSUE THREAD

**Issue by thorodin-roth** [laqieer/ida_gba_stuff#1]
Thank you very much for this repo!
I made a [script ](https://gist.github.com/thorodin-roth/b591807a90ee704fca22c677a566f0f0) similar to your loader but for IDAPython  7.* 
you more then pleased to use it if you like 
https://gist.github.com/thorodin-roth/b591807a90ee704fca22c677a566f0f0

**Comment by laqieer** [comment]
Thanks. Included in README.
